spring:
  application:
    name: data-analyzer-grpc
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:${HOST_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true

server:
  port: 8082

grpc:
  server:
    port: ${GRPC_PORT}